### ISSUE TITLE
Issue with Fog

### ISSUE THREAD

**Issue by The-Order** [zmaster587/AdvancedRocketry#1201]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.2.2624
Advanced Rocketry Version:
- 1.3.0 - 61
LibVulpes Version:
- 0.2.8 - 27
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report: no crash
----------
Explain issue in detail:

There seems to be an issue with how this mod handles fog in Minecraft. When going under water or under lava more than once, the fog will disappear completely resulting in the below screenshot where I am under 3 blocks of flowing lava. Same behavior when under water, the fog disappears completely and it just looks odd, especially under water in oceans.

What's really strange is if you switch between going under water and back to under lava, it comes back until you leave and renter the same liquid again.

![2018-03-10_09 26 57](https://user-images.githubusercontent.com/6519501/37244397-b0838b24-2445-11e8-8485-4525497e6c8e.png)

![2018-03-10_09 33 08](https://user-images.githubusercontent.com/6519501/37244425-2009e65a-2446-11e8-8481-4dfd70572043.png)

![2018-03-10_09 33 25](https://user-images.githubusercontent.com/6519501/37244426-2023618e-2446-11e8-974a-2d8dd7769d4e.png)

The last picture is what underwater looks like normally with the fog.

This was replicated in a vanilla minecraft instance where only advanced rocketry and libvulpes was installed, no other mods. I have also tweaked various config settings for this mod and it has not fixed the issue.

The problem also persists in mod packs as well such as All the mods 3. With Biomes O plenty for example, the ominous woods normally has very thick fog but due to this issue/bug, it is absent when this mod is in the pack.

**Comment by zmaster587** [comment]
Will take a look at AR's fog handler, it sounds like it's pulling the existing fog settings before applying atmosphere effects

**Comment by zmaster587** [comment]
The issues with the water and lava have been fixed, I have yet to see how BOP handles its fog yet

**Comment by The-Order** [comment]
Latest update fixed the issue and was applied to Minecraft 1.10.2 and 1.11.2. But for some reason 1.12.2 version of Advanced Rocketry didn't get the update FYI, still broken in that version of the mod.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.3.0.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1817716/AdvancedRocketry-1.12.2-1.3.0.jar.zip)
Can you try this build and see if it works out?  I do not expect it will help with BoP, that's a whole different issue I think.

**Comment by The-Order** [comment]
That version did fix the water and lava fog issue with 1.12.2, but you are correct that it does not fix the issue with Biomes O Plenty fog. 

Something I also noticed is with Optifine in the mod pack along side Advanced Rocketry, the fog distance setting in the graphics options does not work. It seems to default to the further distance from the player. Changing the setting to 0.6 or 0.2 doesn't change were the fog starts at the edge of the draw distance. Perhaps it is something further related to how this mod handles the fog as it does work when Advanced Rocketry is removed.

**Comment by zmaster587** [comment]
Advanced Rocketry overrides default fog distance for atmospheric effects.  Right now I still need to do more research into getting fog distance without ASM hacks.  For for the time being, the fog distance in BoP and Optifine will be broken until some way can be found to actually get the values other mods set.  That can be done very easily with fog color at least though.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Korvynus** [comment]
Sorry to necro this but yes I'm experiencing the same issue. No fog underwater or lava and the thick fog in vampirism biome is gone too. It brokes the fog setting in OptiFine as well. I really hope for a fix someday or a workaround maybe.

**Comment by githubuser49** [comment]
> Sorry to necro this but yes I'm experiencing the same issue. No fog underwater or lava and the thick fog in vampirism biome is gone too. It brokes the fog setting in OptiFine as well. I really hope for a fix someday or a workaround maybe.

there is supposed to be fog, it's a big part of the mod, optifine removes fog, adv rocketry can't do anything about it
