### ISSUE TITLE
Warp Controller NPE Crash

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1254]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.

## Have you verified this is an issue in the latest unstable build
Unsure, using build from Discord posted April 14 at 1:50 AM CDT

## Version of LibVulpes
 LibVulpes-1.12.2-0.2.8-29

## Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

## Crash report or log (if applicable)
https://pastebin.com/8Dvprg6j

## Description of the problem
Place a filled data storage unit into the wrong IO slot, IE mass in distance column.
Click "Store to Buffer" and it should update the proper column stored bar
Click "Store to Buffer" a second time with the now empty data storage in IO slot and crash

**Comment by zmaster587** [comment]
Fixed in 1,12.2-1.4.0-74

**Comment by TotalHamman** [comment]
Crash is still occurring with 1.12.2-1.4.0-76.  Recreated in pack with only:  
* AdvancedRocketry 1.12.2-1.4.0-76  
* Vulpes Library 1.12.2-0.2.8-29  
* jei_1.12.2-4.9.0.163  
* theoneprobe-1.12-1.4.22.jar  

Gif of the steps to recreate  --  https://gyazo.com/c1ee08091451079a129d7bb3b04e797d

**Comment by zmaster587** [comment]
my apologies, I thought you were saying you put a filled chip in, drained it, then took it out and tried to fill the data without a chip in the slot.

**Comment by zmaster587** [comment]
Tested, appears to be fixed
