### ISSUE TITLE
oregen and artifact data being stripped on world save

### ISSUE THREAD

**Issue by phit** [zmaster587/AdvancedRocketry#1325]
## Version of Advanced Rocketry
latest from github 961fc5502de1cf24853d3aef498822a2dbf30b97
## Have you verified this is an issue in the latest unstable build
yes
## Crash report or log (if applicable)
log 
![image](https://user-images.githubusercontent.com/2097483/40906329-cadff3f2-67e0-11e8-8df3-989018982bb6.png)
patch to get that log: https://gist.github.com/phit/96a86ff5c1d52927432c9d68112b8781

## Description of the problem
oregen and artifact data is loaded fine from file but then not written back on world save, I can reproduce this every time this way:

use this config and make a new world: https://gist.github.com/phit/012e565bbfbb26cc81dbde84e64fd425
stop server, start server, data is gone
stop server again, replace planetdefs.xml in world folder with gist from above and start server again, then run save-all
the data will be gone again, you can repeat the last step as much as you like for easy testing

tested with these additional mods 
jei_1.12.2-4.9.2.196.jar
LibVulpes-1.12.2-0.2.8-32-universal.jar
valkyrielib-1.12.2-2.0.10b.jar
environmentaltech-1.12.2-2.0.10a.jar

video https://phit.link/s/2018-06-04_10-18-09.mp4

**Comment by phit** [comment]
so the issue is in XMLPlanetLoader
https://github.com/zmaster587/AdvancedRocketry/blob/6a47627d752245af1e02a700d69f403aa4140da9/src/main/java/zmaster587/advancedRocketry/util/XMLPlanetLoader.java#L512

planets in `StellarBody` never has the data for oregen or artifacts, only `dimensionList` in the `DimensionManager` instance does

**Comment by phit** [comment]
welp I fixed it for our server, this seems to work well
https://gist.github.com/phit/366611cef361a856ddad50409c309e25

in general the whole system of dimlist and galaxy seems like a mess, also even after going through all of that it's still not clear to me why all stuff is saved to xml but only some stuff is actually loaded from it?

**Comment by zmaster587** [comment]
It's a hybrid of two systems at the moment and desperately needs to be refactored, originally there was only the dat file, but people kept asking for more user configurable features and so things kinda migrated over time, the problem is actually likely where the two systems intersect in the AdvancedRocketry:serverStarting event and the data is not properly being transferred around.

Ideally everything is going to be moved over to the XML, I've just need to find time to do it though.

**Comment by zmaster587** [comment]
I think it may have been fixed by 01317ec7d329b04687e0ce7f41141046b5ff9911

**Comment by phit** [comment]
that did not fix it, `dimCouplingList` has all the correct data, see the patch log in my initial issue.
the problem is during saving, not during the loading, the data is being loaded correctly just not saved back correctly 

see https://github.com/Stonebound/AdvancedRocketry/commit/c8a577a255f856a84699349bc3ef5b699faa08ec for how i fixed it

**Comment by zmaster587** [comment]
For some reason the issue is not present in single player, found out it's caused by a missing star assignment in serverStarting, now confirmed and fixed in multiplayer.
