### ISSUE TITLE
Padded Landing Boots Cannot Be Crafted [BUG]

### ISSUE THREAD

**Issue by dtrent1** [zmaster587/AdvancedRocketry#1626]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.6.0-153

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.12.2-0.4.1-59

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Description of the problem
>The Padded Landing Boots cannot be crafted in the Precision Assembling Machine. When the components are put into an input hatch of a functional Precision Assembling Machine, the Bionic Leg Upgrade is crafted instead. Both items require an Advanced Circuit and Control Circuit Board. Possible solution is to use a different circuit board or the Basic Circuit in one of the recipes for the Padded Landing Boots or the Bionic Leg.

**Comment by zmaster587** [comment]
There's supposed to be a motor required for the legs, however it's looking like the ore dict entry for the motor is being created AFTER loading the recipes for some reason.

**Comment by zmaster587** [comment]
Fixed in 03ff5a9519cf0c28ae4e7e12da3d7fc009daded0 and libvulpes build 60

**Comment by ErdbeerbaerLP** [comment]
On my modapck server (which has build 60) it is still broken
