### ISSUE TITLE
Build rocket crash

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2029]
## Version of Advanced Rocketry
1.16.5-1.7.1-5

## Version of LibVulpes
1.16.5-1-0-1-8

## Version of Minecraft
1.16.5

## Crash report
https://paste.ee/p/WkLj9

## Description of the problem
Build a rocket, click on build, crash

**Comment by zmaster587** [comment]
Can you replicate this crash without other mods installed or can you narrow it down to a few?  
If it doesn't crash with just AR and libvulpes, I assume it could be whatever mod is developed by somebody named chocolate given the stack trace print, that might help narrow things down.

**Comment by dotada** [comment]
I got kinda the same problem except for me it doesnt crash my game it crashes the server im playing on

**Comment by zmaster587** [comment]
@dotada Is that with only Advanced rocketry and libvulpes?

**Comment by dotada** [comment]
> @dotada Is that with only Advanced rocketry and libvulpes?

Yep

**Comment by zmaster587** [comment]
> > @dotada Is that with only Advanced rocketry and libvulpes?
> 
> Yep

Can you get me a log with only AR and libvulpes loaded then?  The log you sent here has a bunch of mods in there and the crash agentwolf posted explicitly refers to chocolate-1.2.0-1.16.4 so that kinda muddies things a bit.

**Comment by DIO-CAMELOT** [comment]
Crash after rocket build.





---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11.04.21 17:17
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.block.RedstoneDiodeBlock.func_176398_g(RedstoneDiodeBlock.java:83) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneDiodeBlock.func_220069_a(RedstoneDiodeBlock.java:66) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock.java:583) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_190524_a(World.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.world.World.func_195593_d(World.java:299) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.block.RedstoneWireBlock.func_235547_a_(RedstoneWireBlock.java:224) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneWireBlock.func_220069_a(RedstoneWireBlock.java:312) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock.java:583) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_190524_a(World.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlock.java:168) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlock.java:153) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock.java:612) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:283) ~[?:?] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.setBlockState(StorageChunk.java:216) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.copyWorldBB(StorageChunk.java:603) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.cutWorldBB(StorageChunk.java:710) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.assembleRocket(TileRocketBuilder.java:443) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.performFunction(TileRocketBuilder.java:209) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.libVulpes.tile.TileEntityRFConsumer.func_73660_a(TileEntityRFConsumer.java:101) ~[libvulpes:unspecified] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.RedstoneDiodeBlock.func_176398_g(RedstoneDiodeBlock.java:83) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneDiodeBlock.func_220069_a(RedstoneDiodeBlock.java:66) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock.java:583) ~[?:?] {re:classloading}
-- Block being updated --
Details:
	Source block type: ID #minecraft:redstone_wire (block.minecraft.redstone_wire // net.minecraft.block.RedstoneWireBlock)
	Block: Block{minecraft:repeater}[delay=4,facing=south,locked=false,powered=true]
	Block location: World: (3,14,8), Chunk: (at 3,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.world.World.func_195593_d(World.java:299) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.block.RedstoneWireBlock.func_235547_a_(RedstoneWireBlock.java:224) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneWireBlock.func_220069_a(RedstoneWireBlock.java:312) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock.java:583) ~[?:?] {re:classloading}


-- Block being updated --
Details:
	Source block type: ID #minecraft:repeater (block.minecraft.repeater // net.minecraft.block.RepeaterBlock)
	Block: Block{minecraft:redstone_wire}[east=side,north=none,power=0,south=side,west=none]
	Block location: World: (3,14,7), Chunk: (at 3,0,7 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlock.java:168) ~[?:?] {re:classloading}
	at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlock.java:153) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock.java:612) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:283) ~[?:?] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.setBlockState(StorageChunk.java:216) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.copyWorldBB(StorageChunk.java:603) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.util.StorageChunk.cutWorldBB(StorageChunk.java:710) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.assembleRocket(TileRocketBuilder.java:443) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.performFunction(TileRocketBuilder.java:209) ~[advancedrocketry:unspecified] {re:classloading}
	at zmaster587.libVulpes.tile.TileEntityRFConsumer.func_73660_a(TileEntityRFConsumer.java:101) ~[libvulpes:unspecified] {re:classloading}


-- Block entity being ticked --
Details:
	Name: advancedrocketry:rocket_builder // zmaster587.advancedRocketry.tile.TileRocketBuilder
	Block: Block{advancedrocketry:rocketassembler}[facing=west,state=false]
	Block location: World: (-176,65,-153), Chunk: (at 0,4,7 in -11,-10; contains blocks -176,0,-160 to -161,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{advancedrocketry:rocketassembler}[facing=west,state=false]
	Block location: World: (-176,65,-153), Chunk: (at 0,4,7 in -11,-10; contains blocks -176,0,-160 to -161,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['DIO_CAMELOT'/10559, l='ServerLevel[Новый мир]', x=-178.40, y=64.00, z=-152.44]]
	Chunk stats: ServerChunkCache: 2518
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,66,-48), Chunk: (at 0,4,0 in -14,-3; contains blocks -224,0,-48 to -209,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 242938 game time, 183266 day time
	Level name: Новый мир
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 140101 (now: false), thunder time: 11010 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-70-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2780435296 bytes (2651 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.1
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.1-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.1-universal.jar                 |Forge                         |forge                         |36.1.1              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AdvancedRocketry-1.16.5-1.7.1-8-universal.jar     |Advanced Rocketry             |advancedrocketry              |1.16.5-1.7.1-8      |DONE      |NOSIGNATURE
		LibVulpes-1.16.5-1.0.1-14-universal.jar           |Lib Vulpes                    |libvulpes                     |1.16.5-1.0.1-14     |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.73.jar                           |Just Enough Items             |jei                           |7.6.1.73            |DONE      |NOSIGNATURE
	Crash Report UUID: 899b60a5-d677-4d75-bf91-8f7275318fe1
	Player Count: 1 / 8; [ServerPlayerEntity['DIO_CAMELOT'/10559, l='ServerLevel[New world]', x=-178.40, y=64.00, z=-152.44]]
	Data Packs: vanilla, mod:forge, mod:advancedrocketry, mod:libvulpes, mod:jei
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by zmaster587** [comment]
@DIO-CAMELOT Can you send a pic of the rocket you were trying to build?  It looks like it's related to redstone somehow and simply building a rocket with a redstone circuit isn't causing a crash for me

**Comment by agentwolf88** [comment]
[crash-2021-04-13_19.05.15-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6305454/crash-2021-04-13_19.05.15-server.txt)

Still crashs with click on "build"

**Comment by zmaster587** [comment]
> [crash-2021-04-13_19.05.15-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6305454/crash-2021-04-13_19.05.15-server.txt)
> 
> Still crashs with click on "build"


@agentwolf88 that particular issue is fixed for next build. (was reported in #2046), it also appears unrelated to the original crash.  Until the next build comes out, you can avoid the issue you reported in your last comment by using single player.

**Comment by agentwolf88** [comment]
[crash-2021-04-14_11.54.26-client.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6309999/crash-2021-04-14_11.54.26-client.txt)

Still crashs in AdvancedRocketry-1.16.5-2.0.0-10-universal.jar :(

**Comment by zmaster587** [comment]
> [crash-2021-04-14_11.54.26-client.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6309999/crash-2021-04-14_11.54.26-client.txt)
> 
> Still crashs in AdvancedRocketry-1.16.5-2.0.0-10-universal.jar :(

AR 20.0.0-10 requires libvulpes 1.16.5-1.0.2-17, it looks like you're on 1.16.5-1.0.2-16

https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/3274510

**Comment by agentwolf88** [comment]
Ok, my bad.

**Comment by zmaster587** [comment]
Advanced rocketry build 11 should hopefully resolve this issue.
